Update ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -20,7 +20,7 @@ concurrency:
 
 jobs:
   pytest:
-    name: Run Pytest python - ${{ matrix.PYTHON_VERSION }}
+    name: Run pytest python - ${{ matrix.PYTHON_VERSION }}
     runs-on: "ubuntu-latest"
     strategy:
       matrix:
@@ -28,3 +28,31 @@ jobs:
     steps:
       - name: Check out source code
         uses: actions/checkout@v4
+
+      - name: Setup python
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.PYTHON_VERSION }}
+
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip -r requirements-dev.txt
+          pip install -e .
+
+      - name: Test with pytest
+        run: |
+          python3 -m pytest --color=yes --cov --durations=0 && exit_code=0|| exit_code=$?
+          # don't fail if no tests were collected, e.g. for test_licence.py
+          if [ "${exit_code}" -eq 5 ]; then
+            echo "No tests were collected"
+            exit 0
+          elif [ "${exit_code}" -ne 0 ]; then
+            echo "Tests failed with exit code ${exit_code}"
+            exit 1
+          fi
+
+      - name: Upload coverage
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage_${{ matrix.test }}
+          path: .coverage
